name: test

# Run this workflow on pushes and manually
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: .go-version

      - name: Run Tests
        run: go test -v ./...

      - name: Run Build
        run: go build
